const stationCodes = {
    "Agartala" : "VEAT",
    "Agatti Island" : "VOAT",
    "Agra" : "VIAG",
    "Ahmedabad" : "VAAH",
    "Aizwal" : "VELP",
    "Allahabad" : "VEAB",
    "Amritsar" : "VIAR",
    "Arkonam" : "VOAR",
    "Aurangabad" : "VAAU",
    "Baghdogra" : "VEBD",
    "Bangalore" : "VOBG",
    "Bangalore " : "VOBL",
    "Bareilly" : "VIBY",
    "Baroda" : "VABO",
    "Belgaum" : "VOBM",
    "Bhaunager": "VABV",
    "Bhopal" : "VABP",
    "Bhubaneswar": "VEBS",
    "Bhuj": "VABJ",
    "Bikaner": "VIBK",
    "Bilaspur": "VEBU",
    "Calicut": "VOCL",
    "Campbell": "VOBX",
    "Car Nicobar": "VECX",
    "Chandigarh":"VICG",
    "Coimbatore":"VOCB",
    "Cooch-behar":"VECO",
    "Cuddapah": "VOCP",
    "Dehra Dun": "VIDN",
    "Delhi" : "VIDD",
    "New Delhi " : "VIDP",
    "Deoghar":"VEDO",
    "Dimapur":"VEMR",
    "Diu":"VADU",
    "Durgapur":"VEDG",
    "Fursatganj":"VERB",
    "Gaya":"VEGY",
    "Goa":"VOGO",
    "Gondia":"VAGD",
    "Gorakhpur":"VEGK",
    "Gulbarga":"VOGB",
    "Guwahati":"VEGT",
    "Gwalior":"VIGR",
    "Hashimara":"VEHX",
    "Hollongi":"VEHO",
    "Hubli":"VOHB",
    "Hyderabad":"VOHY",
    "Hyderabad ":"VOHS",
    "Hyderabad-Port":"VOSH",
    "INS Parundu":"VORM",
    "Imphal":"VEIM",
    "Indore":"VAID",
    "Jabalpur":"VAJB",
    "Jagdalpur":"VEJR",
    "Jaipur" : "VIJP",
    "Jaisalmer":"VIJR",
    "Jalgaon":"VAJL",
    "Jammu":"VIJU",
    "Jamnagar":"VAJM",
    "Jamshedpur":"VEJS",
    "Jharsuguda":"VEJH",
    "Jodhpur":"VIJO",
    "Jorhat":"VEJT",
    "Kalaikunda":"VEDX",
    "Kandla":"VAKE",
    "Kangra":"VIGG",
    "Kannur":"VOKN",
    "Kishangarh":"VIKG",
    "Kochi":"VOCI",
    "Kolhapur":"VAKP",
    "Kolkata":"VECC",
    "Kota":"VIKO",
    "Kulu":"VIBR",
    "Kurnool":"VOKU",
    "Kushinagar":"VEKI",
    "Leh":"VILH",
    "Lilabari":"VELR",
    "Lucknow":"VILK",
    "Ludhiaha":"VILD",
    "Madras":"VOMM",
    "Madurai":"VOMD",
    "Mangalore":"VOML",
    "Mohanbari":"VEMN",
    "Mopa":"VOGA",
    "Mumbai":"VABB",
    "Navi Mumbai ":"VAJJ",
    "Mysore":"VOMY",
    "Nagpur":"VANP",
    "Nainital":"VIPT",
    "Nanded":"VOND",
    "Nasik Ojhar AFS":"VAOZ",
    "Pakyong":"VEPY",
    "Patina":"VEPT",
    "Pundicherry":"VOPC",
    "Porbandar":"VAPR",
    "Port Blair":"VOPB",
    "Pune":"VAPO",
    "Raipur":"VERP",
    "Rajahmundry":"VORY",
    "Rajkot":"VARK",
    "Ranchi":"VERC",
    "Rourkela":"VERK",
    "Rupsi":"VERU",
    "Salem":"VOSM",
    "Shillong":"VEBI",
    "Shimla":"VISM",
    "Shirdi":"VASD",
    "Sindhudurg":"VOSR",
    "Srinagar":"VISR",
    "Surat":"VASU",
    "Tezpur":"VETZ",
    "Thanjavur":"VOTJ",
    "Thoise":"VITE",
    "Tiruchirappalli":"VOTR",
    "Tirupeti":"VOTP",
    "Trivandrum":"VOTV",
    "Tuticorin":"VOTK",
    "Udaipur":"VAUD",
    "Varanasi":"VEBN",
    "Vizagapatam":"VOVZ"
}